import { FolderStructure } from '../types';

export const angularStandaloneStructure: FolderStructure = {
  id: 'angular-standalone',
  name: 'Angular 18 Standalone',
  description: 'Angular 18 application with standalone components architecture',
  framework: 'angular',
  structure: 'standalone',
  directories: [
    'src',
    'src/app',
    'src/app/core',
    'src/app/core/services',
    'src/app/core/guards',
    'src/app/core/interceptors',
    'src/app/core/models',
    'src/app/shared',
    'src/app/shared/components',
    'src/app/shared/directives',
    'src/app/shared/pipes',
    'src/app/shared/utils',
    'src/app/features',
    'src/app/features/home',
    'src/app/features/home/components',
    'src/app/features/home/services',
    'src/app/features/auth',
    'src/app/features/auth/components',
    'src/app/features/auth/services',
    'src/app/features/auth/guards',
    'src/app/features/dashboard',
    'src/app/features/dashboard/components',
    'src/app/features/dashboard/services',
    'src/assets',
    'src/assets/images',
    'src/assets/icons',
    'src/assets/styles',
    'src/environments',
    'public',
    'tests',
    'tests/unit',
    'tests/integration',
    'tests/e2e',
    'docs',
  ],
};

export const angularFeatureBasedStructure: FolderStructure = {
  id: 'angular-feature-based',
  name: 'Angular Feature-Based',
  description: 'Angular 18 application with feature-based modular architecture',
  framework: 'angular',
  structure: 'feature-based',
  directories: [
    'src',
    'src/app',
    'src/app/core',
    'src/app/core/services',
    'src/app/core/guards',
    'src/app/core/interceptors',
    'src/app/core/models',
    'src/app/core/constants',
    'src/app/shared',
    'src/app/shared/components',
    'src/app/shared/components/ui',
    'src/app/shared/components/layout',
    'src/app/shared/directives',
    'src/app/shared/pipes',
    'src/app/shared/utils',
    'src/app/shared/validators',
    'src/app/features',
    'src/app/features/home',
    'src/app/features/home/components',
    'src/app/features/home/services',
    'src/app/features/home/models',
    'src/app/features/auth',
    'src/app/features/auth/components',
    'src/app/features/auth/services',
    'src/app/features/auth/guards',
    'src/app/features/auth/models',
    'src/app/features/dashboard',
    'src/app/features/dashboard/components',
    'src/app/features/dashboard/services',
    'src/app/features/dashboard/models',
    'src/app/features/profile',
    'src/app/features/profile/components',
    'src/app/features/profile/services',
    'src/app/features/profile/models',
    'src/assets',
    'src/assets/images',
    'src/assets/icons',
    'src/assets/styles',
    'src/environments',
    'public',
    'tests',
    'tests/unit',
    'tests/integration',
    'tests/e2e',
    'docs',
  ],
};

export const angularModuleBasedStructure: FolderStructure = {
  id: 'angular-module-based',
  name: 'Angular Module-Based',
  description:
    'Angular application with traditional NgModule architecture for legacy support',
  framework: 'angular',
  structure: 'module-based',
  directories: [
    'src',
    'src/app',
    'src/app/core',
    'src/app/core/services',
    'src/app/core/guards',
    'src/app/core/interceptors',
    'src/app/shared',
    'src/app/shared/components',
    'src/app/shared/directives',
    'src/app/shared/pipes',
    'src/app/modules',
    'src/app/modules/home',
    'src/app/modules/home/components',
    'src/app/modules/home/services',
    'src/app/modules/auth',
    'src/app/modules/auth/components',
    'src/app/modules/auth/services',
    'src/app/modules/dashboard',
    'src/app/modules/dashboard/components',
    'src/app/modules/dashboard/services',
    'src/assets',
    'src/assets/images',
    'src/assets/icons',
    'src/assets/styles',
    'src/environments',
    'public',
    'tests',
    'tests/unit',
    'tests/integration',
    'tests/e2e',
    'docs',
  ],
};
