import { FolderStructure } from '../types';

export const nestjsModularStructure: FolderStructure = {
  id: 'nestjs-modular',
  name: 'NestJS Modular Architecture',
  description:
    'NestJS application with modular architecture, shared modules, and feature-based modules',
  framework: 'nestjs',
  structure: 'modular',
  directories: [
    'src',
    'src/app',
    'src/app/modules',
    'src/app/modules/auth',
    'src/app/modules/auth/controllers',
    'src/app/modules/auth/services',
    'src/app/modules/auth/dtos',
    'src/app/modules/users',
    'src/app/modules/users/controllers',
    'src/app/modules/users/services',
    'src/app/modules/users/dtos',
    'src/app/modules/products',
    'src/app/modules/products/controllers',
    'src/app/modules/products/services',
    'src/app/modules/products/dtos',
    'src/app/common',
    'src/app/common/guards',
    'src/app/common/interceptors',
    'src/app/common/filters',
    'src/app/common/pipes',
    'src/app/common/utils',
    'src/app/shared',
    'src/app/shared/interfaces',
    'src/app/shared/constants',
    'src/config',
    'src/config/database',
    'src/config/env',
    'src/config/logger',
    'src/config/swagger',
    'src/utils',
    'src/utils/helpers',
    'src/utils/validators',
    'src/types',
    'src/constants',
    'src/tests',
    'src/tests/unit',
    'src/tests/integration',
    'src/tests/e2e',
    'docs',
  ],
};

export const fastifyPluginBasedStructure: FolderStructure = {
  id: 'fastify-plugin-based',
  name: 'Fastify Plugin-Based Architecture',
  description:
    'Fastify application organized around plugins, routes, schemas, and services',
  framework: 'fastify',
  structure: 'plugin-based',
  directories: [
    'src',
    'src/plugins',
    'src/plugins/auth',
    'src/plugins/users',
    'src/plugins/database',
    'src/plugins/logger',
    'src/routes',
    'src/routes/auth',
    'src/routes/users',
    'src/routes/products',
    'src/services',
    'src/services/auth',
    'src/services/users',
    'src/services/products',
    'src/controllers',
    'src/schemas',
    'src/schemas/auth',
    'src/schemas/users',
    'src/config',
    'src/config/env',
    'src/config/logger',
    'src/config/database',
    'src/utils',
    'src/utils/helpers',
    'src/utils/validators',
    'src/types',
    'src/constants',
    'tests',
    'tests/unit',
    'tests/integration',
    'tests/e2e',
    'docs',
  ],
};

export const koaMiddlewareStructure: FolderStructure = {
  id: 'koa-middleware',
  name: 'Koa Middleware Architecture',
  description:
    'Koa application structured around middleware, routes, controllers, and services',
  framework: 'koa',
  structure: 'middleware',
  directories: [
    'src',
    'src/app',
    'src/middleware',
    'src/middleware/auth',
    'src/middleware/error',
    'src/middleware/validation',
    'src/middleware/logging',
    'src/routes',
    'src/routes/auth',
    'src/routes/users',
    'src/routes/products',
    'src/controllers',
    'src/services',
    'src/models',
    'src/config',
    'src/config/env',
    'src/config/logger',
    'src/utils',
    'src/utils/helpers',
    'src/utils/validators',
    'src/types',
    'src/constants',
    'tests',
    'tests/unit',
    'tests/integration',
    'tests/e2e',
    'docs',
  ],
};
