import { FolderStructure } from '../types';

export const nextjsAppRouterStructure: FolderStructure = {
  id: 'nextjs-app-router',
  name: 'Next.js 15 App Router',
  description: 'Next.js 15 application with App Router and server components',
  framework: 'nextjs',
  structure: 'app-router',
  directories: [
    'src',
    'src/app',
    'src/app/(auth)',
    'src/app/(auth)/login',
    'src/app/(auth)/register',
    'src/app/(dashboard)',
    'src/app/(dashboard)/analytics',
    'src/app/(dashboard)/settings',
    'src/app/api',
    'src/app/api/auth',
    'src/app/api/users',
    'src/components',
    'src/components/ui',
    'src/components/shared',
    'src/components/dashboard',
    'src/components/auth',
    'src/lib',
    'src/lib/auth',
    'src/lib/db',
    'src/services',
    'src/services/api',
    'src/hooks',
    'src/contexts',
    'src/utils',
    'src/utils/helpers',
    'src/utils/validators',
    'src/types',
    'src/constants',
    'src/styles',
    'public',
    'public/assets',
    'public/assets/images',
    'public/assets/icons',
    'tests',
    'tests/unit',
    'tests/integration',
    'tests/e2e',
    'docs',
  ],
};

export const nextjsPagesRouterStructure: FolderStructure = {
  id: 'nextjs-pages-router',
  name: 'Next.js Pages Router',
  description: 'Next.js application with traditional Pages Router architecture',
  framework: 'nextjs',
  structure: 'pages-router',
  directories: [
    'src',
    'src/pages',
    'src/pages/api',
    'src/pages/api/auth',
    'src/pages/api/users',
    'src/pages/auth',
    'src/pages/dashboard',
    'src/components',
    'src/components/ui',
    'src/components/common',
    'src/components/layout',
    'src/hooks',
    'src/services',
    'src/services/api',
    'src/utils',
    'src/utils/helpers',
    'src/utils/validators',
    'src/lib',
    'src/lib/auth',
    'src/lib/db',
    'src/contexts',
    'src/types',
    'src/constants',
    'src/styles',
    'public',
    'public/assets',
    'public/assets/images',
    'public/assets/icons',
    'tests',
    'tests/unit',
    'tests/integration',
    'tests/e2e',
    'docs',
  ],
};

export const nextjsFeatureBasedStructure: FolderStructure = {
  id: 'nextjs-feature-based',
  name: 'Next.js Feature-Based',
  description:
    'Next.js application with feature-based domain-driven architecture',
  framework: 'nextjs',
  structure: 'feature-based',
  directories: [
    'src',
    'src/app',
    'src/app/api',
    'src/features',
    'src/features/auth',
    'src/features/auth/components',
    'src/features/auth/hooks',
    'src/features/auth/services',
    'src/features/auth/types',
    'src/features/auth/utils',
    'src/features/dashboard',
    'src/features/dashboard/components',
    'src/features/dashboard/hooks',
    'src/features/dashboard/services',
    'src/features/dashboard/types',
    'src/features/dashboard/utils',
    'src/features/profile',
    'src/features/profile/components',
    'src/features/profile/hooks',
    'src/features/profile/services',
    'src/features/profile/types',
    'src/features/profile/utils',
    'src/shared',
    'src/shared/components',
    'src/shared/hooks',
    'src/shared/lib',
    'src/shared/services',
    'src/shared/utils',
    'src/shared/types',
    'src/shared/constants',
    'src/styles',
    'public',
    'public/assets',
    'tests',
    'tests/unit',
    'tests/integration',
    'tests/e2e',
    'docs',
  ],
};

export const nextjsMonorepoStructure: FolderStructure = {
  id: 'nextjs-monorepo',
  name: 'Next.js Monorepo',
  description: 'Next.js monorepo structure with apps and packages',
  framework: 'nextjs',
  structure: 'monorepo',
  directories: [
    'apps',
    'apps/web',
    'apps/web/src',
    'apps/web/src/app',
    'apps/web/src/components',
    'apps/web/public',
    'apps/admin',
    'apps/admin/src',
    'apps/admin/src/app',
    'apps/admin/src/components',
    'apps/admin/public',
    'packages',
    'packages/ui',
    'packages/ui/src',
    'packages/ui/src/components',
    'packages/config',
    'packages/config/eslint',
    'packages/config/typescript',
    'packages/utils',
    'packages/utils/src',
    'packages/types',
    'packages/types/src',
    'docs',
  ],
};
