import { FolderStructure } from '../types';

export const vueCompositionApiStructure: FolderStructure = {
  id: 'vue-composition-api',
  name: 'Vue 3 Composition API',
  description:
    'Vue 3 application with Composition API and modern best practices',
  framework: 'vue',
  structure: 'composition-api',
  directories: [
    'src',
    'src/assets',
    'src/assets/images',
    'src/assets/icons',
    'src/assets/styles',
    'src/components',
    'src/components/ui',
    'src/components/common',
    'src/components/layout',
    'src/composables',
    'src/stores',
    'src/views',
    'src/router',
    'src/services',
    'src/services/api',
    'src/utils',
    'src/utils/helpers',
    'src/utils/validators',
    'src/types',
    'src/constants',
    'src/plugins',
    'public',
    'public/assets',
    'tests',
    'tests/unit',
    'tests/unit/components',
    'tests/unit/composables',
    'tests/unit/stores',
    'tests/e2e',
    'docs',
  ],
};

export const nuxt3AppRouterStructure: FolderStructure = {
  id: 'nuxt3-app-router',
  name: 'Nuxt 3 App Router',
  description: 'Nuxt 3 application with App Router and server-side rendering',
  framework: 'vue',
  structure: 'nuxt3',
  directories: [
    'assets',
    'assets/css',
    'assets/images',
    'assets/icons',
    'components',
    'components/ui',
    'components/common',
    'components/layout',
    'composables',
    'layouts',
    'middleware',
    'pages',
    'pages/auth',
    'pages/dashboard',
    'plugins',
    'public',
    'public/assets',
    'server',
    'server/api',
    'server/middleware',
    'server/routes',
    'server/utils',
    'stores',
    'types',
    'utils',
    'utils/helpers',
    'utils/validators',
    'tests',
    'tests/unit',
    'tests/e2e',
    'docs',
  ],
};

export const vueOptionsApiStructure: FolderStructure = {
  id: 'vue-options-api',
  name: 'Vue 3 Options API',
  description:
    'Vue 3 application with traditional Options API for backward compatibility',
  framework: 'vue',
  structure: 'options-api',
  directories: [
    'src',
    'src/assets',
    'src/assets/images',
    'src/assets/icons',
    'src/assets/styles',
    'src/components',
    'src/components/common',
    'src/components/layout',
    'src/mixins',
    'src/directives',
    'src/filters',
    'src/views',
    'src/router',
    'src/store',
    'src/store/modules',
    'src/services',
    'src/services/api',
    'src/utils',
    'src/constants',
    'src/plugins',
    'public',
    'public/assets',
    'tests',
    'tests/unit',
    'tests/e2e',
    'docs',
  ],
};

export const vueFeatureBasedStructure: FolderStructure = {
  id: 'vue-feature-based',
  name: 'Vue 3 Feature-Based',
  description:
    'Vue 3 application with feature-based domain-driven architecture',
  framework: 'vue',
  structure: 'feature-based',
  directories: [
    'src',
    'src/features',
    'src/features/auth',
    'src/features/auth/components',
    'src/features/auth/composables',
    'src/features/auth/services',
    'src/features/auth/stores',
    'src/features/auth/types',
    'src/features/auth/views',
    'src/features/dashboard',
    'src/features/dashboard/components',
    'src/features/dashboard/composables',
    'src/features/dashboard/services',
    'src/features/dashboard/stores',
    'src/features/dashboard/types',
    'src/features/dashboard/views',
    'src/features/profile',
    'src/features/profile/components',
    'src/features/profile/composables',
    'src/features/profile/services',
    'src/features/profile/stores',
    'src/features/profile/types',
    'src/features/profile/views',
    'src/shared',
    'src/shared/components',
    'src/shared/composables',
    'src/shared/services',
    'src/shared/utils',
    'src/shared/types',
    'src/shared/constants',
    'src/router',
    'src/assets',
    'src/assets/images',
    'src/assets/icons',
    'src/assets/styles',
    'public',
    'public/assets',
    'tests',
    'tests/unit',
    'tests/e2e',
    'docs',
  ],
};
